name: MobWavePL
version: 1.0.0
main: MobWave.MobWaveMain
commands:
  mob:
    description: モブのスポーンを開始
    usage: /<command>
    default: true
  opengui:
    description: waveGUIを開く
    usage: /<command>
    default: true
  coin:
    description: coin操作コマンド
    usage: /<command>
    default: true
  villager:
    description: shop操作コマンド
    usage: /<command>
    default: true