name: MobWavePL
version: 1.0.0
main: MobWave.MobWaveMain
command:
  mobstart:
    description: モブのスポーンを開始
    usage: /<command>
    default: true
  mobstop:
    description: モブのスポーンを開始
    usage: /<command>
    default: true
